FROM node:latest as build-env
WORKDIR /app
COPY ./package.json ./gulpfile.js ./webpack.config.js ./tsconfig.json ./
COPY ./sass ./sass
COPY ./ts ./ts
RUN npm install
RUN npx webpack --mode production

FROM nginx:latest
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=build-env /app/wwwroot /app
COPY ./wwwroot /app
