FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app
COPY ./*.csproj ./*.cs ./**/*.cs ./
COPY ./Views ./Views
RUN dotnet publish -c Release -o out

FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app/out .
ENV LANG=en_GB.UTF-8
ENTRYPOINT ["dotnet", "Flappy.dll"]
